apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: crud-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crud-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
